version: '2'
services:
    uashield:
      build: .
      restart: always
      container_name: uashield
      image: uashield:latest
      environment:
        WORKERS: '0' #fix before the release
        USEPROXY: 'false'
        DNS_WORKERS: '512' #fix before the release
      networks:
        - shield

networks:
  shield:
    driver: bridge
